# FILES
defaults: # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade
  - train/data: msmarco
  - train/model: splade
  ############## INDEX ###################################
  - index: msmarco
  ############## RETRIEVE ################################
  - retrieve_evaluate: all
  ############### FLOPS ##################################
  - flops: msmarco

# Direct PARAMETER setting
config: # to be provided for each run
  loss: InBatchPairwiseNLL
  augment_pair: in_batch_negatives
  regularizer:
    FLOPS:
      lambda_q: 0.0003
      lambda_d: 0.0001
      T: 50000
      targeted_rep: rep
      reg: FLOPS
  checkpoint_dir: models/splade_max_base/checkpoint
  index_dir: models/splade_max_base/index
  out_dir: models/splade_max_base/out