defaults:
############## TRAIN ###################################
  - train/config: splade
  - train/data: hf_toy
  - train/model: splade
############## INDEX ###################################
  - index: toy
############## RETRIEVE ################################
  - retrieve_evaluate: toy
############### FLOPS ##################################
  - flops: toy  
################ HF TRAINING ###########################
  - hf: training

# Direct PARAMETER setting
config:
  train_batch_size: 1
  loss: KlDiv
  regularizer:
    FLOPS:
      lambda_d: 5e-3
      T: 50000
      targeted_rep: rep
      reg: FLOPS
    L1:
      lambda_q: 5e-3
      T: 50000
      targeted_rep: rep
      reg: L1
  checkpoint_dir:  ??
  index_dir: ??
  out_dir: ??
  fp16: true
  hf_training: true
